steps:
  # Build training container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'Dockerfile.training',
      '-t', 'gcr.io/$PROJECT_ID/nigerian-audit-trainer:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/nigerian-audit-trainer:latest',
      '.'
    ]

  # Push training container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nigerian-audit-trainer:latest']

  # Build API container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/nigerian-audit-api:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/nigerian-audit-api:latest',
      '.'
    ]

  # Push API container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nigerian-audit-api:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'nigerian-audit-api',
      '--image', 'gcr.io/$PROJECT_ID/nigerian-audit-api:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '4Gi',
      '--cpu', '2'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1800s